[build]
  command = "pnpm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express", "serverless-http"]
  node_bundler = "esbuild"
  included_files = ["node_modules/serverless-http/**"]
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
